## AWS Settings
aws:
  # AWS Region ('us-west-2')
  region: "us-east-1"
  # AWS_SECRET_ACCESS_KEY_ID
  access_key: ""
  # AWS_SECRET_ACCESS_KEY
  secret_key: ""

# Docker Image to use
image:
  name: 453939736419.dkr.ecr.us-east-1.amazonaws.com/aws-ssm
  tag: latest

## RBAC
rbac:
  enabled: true

# Deprecated: host_ssl_dir. Use ssl.mount_host (below)
host_ssl_dir: ""

## SSL Certs
ssl:
  # If ssl.mount_host is true, SSL certs will be mounted from a hostVolume
  mount_host: false
  mount_path: /etc/ssl/certs
  host_path: /etc/ssl/certs

## Kubernetes Master API URL
master_url: ""

# Healthcheck port
metrics_port: 9999

# Pod Annotations
podAnnotations: {}

# Pod Resources
resources: {}
